---
abstract: 'pure Perl RDF inferencing'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
keywords:
  - RDF
  - Reasoning
  - Inference
  - OWL
  - RDFS
  - Rules
  - RL
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-Closure
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Data::UUID: 0
  DateTime: 0
  DateTime::Format::Strptime: 0
  DateTime::Format::XSD: 0
  DateTime::TimeZone: 0
  Error: 0
  Exporter: 0
  MIME::Base64: 0
  Math::BigInt: 0
  Module::Pluggable: 0
  Parse::RecDescent: 0
  RDF::Trine: 0.133
  Scalar::Util: 0
  URI: 0
  XML::LibXML: 0
  common::sense: 0
  namespace::clean: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RDF-Closure
  homepage: http://search.cpan.org/dist/RDF-Closure/
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/viewvc/perlmods/RDF-Closure/
version: 0.000_01
